Transform: AWS::Serverless-2016-10-31
Resources:
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LoginFunction
      Description: !Sub Stack ${AWS::StackName} Function ${ResourceName}
      CodeUri: src/login
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 5
      Tracing: Active
      Architectures:
        - arm64
      Events:
        SmartApi001POSTlogin:
          Type: Api
          Properties:
            Path: /login
            Method: POST
            RestApiId: !Ref SmartApi001
  LoginFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${LoginFunction}
  SmartApi001:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: SmartApi001
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /:
            get:
              responses: {}
          /login:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginFunction.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5